import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.room)
    id 'com.android.library'
    id 'com.android.built-in-kotlin'
    id 'com.google.dagger.hilt.android'
    id 'com.google.devtools.ksp'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

android {
    namespace 'ru.sokolovromann.myshopping.core.data'
    buildToolsVersion '37.0.0'
    compileSdkVersion 37

    defaultConfig {
        minSdk 28

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    room {
        schemaDirectory("$projectDir/schemas")
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    implementation project(':core:domain')
    implementation(libs.android.core)
    implementation(libs.datastore)
    implementation(libs.hilt.android)
    implementation(libs.kotlin.serialization)
    implementation(libs.room.ktx)
    implementation(libs.room.runtime)
    ksp(libs.hilt.compiler)
    ksp(libs.room.compiler)
    androidTestImplementation(libs.test.espresso)
    androidTestImplementation(libs.test.junit.android)
    testImplementation(libs.test.junit)
}