package ru.sokolovromann.myshopping.ui.model

enum class SettingUid {
    NightTheme,
    FontSize,
    Backup,
    DisplayMoney,
    Currency,
    DisplayCurrencyToLeft,
    DisplayMoneyZeros,
    TaxRate,
    DisplayCompletedPurchases,
    DisplayEmptyShoppings,
    StrikethroughCompletedProducts,
    CompletedWithCheckbox,
    DisplayOtherFields,
    DisplayListOfAutocompletes,
    EnterToSaveProducts,
    AfterSaveProduct,
    AfterProductCompleted,
    AfterAddShopping,
    AfterShoppingCompleted,
    AutomaticallyEmptyTrash,
    ColoredCheckbox,
    MaxAutocompletes,
    SwipeProduct,
    SwipeShopping,
    ArchiveShoppingsAsCompleted,
    AddAutocompletes
}