import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'com.android.built-in-kotlin'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'ru.sokolovromann.myshopping.core.ui'
    buildToolsVersion '37.0.0'
    compileSdkVersion 37

    defaultConfig {
        minSdk 28

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        compose = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    api 'androidx.compose.material3:material3:1.4.0'
    api 'androidx.compose.material3:material3-adaptive:1.0.0-alpha06'
    api 'androidx.compose.material3:material3-window-size-class:1.4.0'
    api 'androidx.compose.material:material-icons-extended:1.7.8'
    api 'androidx.compose.ui:ui:1.12.0'
    api 'androidx.compose.ui:ui-tooling-preview:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation 'com.google.android.material:material:1.14.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
}