import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'com.android.built-in-kotlin'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'ru.sokolovromann.myshopping.core.ui'
    buildToolsVersion '37.0.0'
    compileSdkVersion 37

    defaultConfig {
        minSdk 28

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        compose = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    api(libs.activity.compose)
    api(libs.compose.ui)
    api(libs.compose.ui.preview)
    api(libs.material3)
    api(libs.material3.adaptive)
    api(libs.material3.icons)
    api(libs.material3.windowSize)
    implementation(libs.android.core)
}