import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'com.google.dagger.hilt.android'
    id 'com.google.devtools.ksp'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'ru.sokolovromann.myshopping.feature.dictionary'
    buildToolsVersion '37.0.0'
    compileSdkVersion 37

    defaultConfig {
        minSdk 28

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        compose = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    implementation project(':core:domain')
    implementation project(':core:navigation')
    implementation project(':core:ui')
    implementation(libs.android.core)
    implementation(libs.hilt.android)
    implementation(libs.hilt.navigation)
    implementation(libs.kotlin.collections.immutable)
    ksp(libs.hilt.compiler)
}